### ISSUE TITLE
Doesn't load with Sublime Text

### ISSUE THREAD

**Issue by Sainan** [JohnnyMorganz/Luau.tmLanguage#7]
When trying to load the .tmlanguage, I get this error in the console:
```
error parsing lexer: Packages/Luau.tmlanguage/Luau.tmLanguage: Unexpected capture value
```

**Comment by JohnnyMorganz** [comment]
I believe the rewrite should now be usable on Sublime Text. Please let me know if not.

**Comment by Sainan** [comment]
Indeed it is.
